project_id = "jndnvpevsgpapntxaaeq"

[functions.generate-mashup]
verify_jwt = false

[functions.claude-mashup-director]
verify_jwt = false

[functions.stem-separation]
verify_jwt = false

[functions.create-signed-upload]
verify_jwt = true

[functions.youtube-search]
verify_jwt = false
